### ISSUE TITLE
Tapping on a @-mention opens profile in Safari

### ISSUE THREAD

**Issue by jumoru** [pcperini/Tusk---Issues#43] opened 2018-09-06 14:43 UTC
## Expected Behavior

Tapping on a @-mention that's not your own account opens profile in Tusk

## Actual Behavior

Profile is opened in Safari

## Steps to Reproduce the Problem

  1. Tap on a @-mention that's not your own handle

## Specifications

  - Version: 29
  - Platform: iOS 11.4.1
  - Subsystem:

**Comment by pcperini** [comment] 2018-09-12 17:29
Can I ask, where are you tapping an @-mention? 😁

**Comment by jumoru** [comment] 2018-09-12 17:41
Sure 😀 It happens in the "Timeline" and the "Mentions" tab of the app when you click on an @-mention that's not your own handle, f.e. 
![img_2541](https://user-images.githubusercontent.com/27491477/45442951-b1a41a80-b6c3-11e8-9e0b-9c3c17327d12.jpg)

**Comment by pcperini** [comment] 2018-09-12 17:58
Gotcha! This might be duplicate of #39?

**Comment by jumoru** [comment] 2018-09-12 18:06
Not sure whether this is the same as #39 since it also happens with @-mentions which do not belong to the posters account as f.e. in this example when clicking on "@lrick"

https://mastodon.social/@bongo/100649534197989969

**Comment by pcperini** [comment] 2018-09-18 22:08
Not a duplicate, but should be resolved

**Closed as completed by pcperini** 2018-09-18 22:08 UTC
Labels: bug
