### ISSUE TITLE
Text after links is not shown

### ISSUE THREAD

**Issue by bitboxer** [pcperini/Tusk---Issues#42] opened 2018-09-06 08:33 UTC
## Expected Behavior

The text after a link in the text should be visible. 

## Actual Behavior

Everything after the link is not visible

## Steps to Reproduce the Problem

  1. navigate to this toot in tusk https://awooo.club/web/statuses/100677883323958556
  1. see that the text after the link is missing

## Specifications

  - Version: 1.0 29
  - Platform: ios
  - Subsystem:

**Comment by Rewur** [comment] 2018-09-07 05:59
same issue here 
https://chaos.social/@maha/100679324485051829
![img_0008](https://user-images.githubusercontent.com/615655/45201016-c754b280-b273-11e8-9e3c-37763fd1bc2d.PNG)

Specifications
Version: 1.0 29
Platform: iOS 11.4.1
System: iPhone X

**Comment by pcperini** [comment] 2018-09-11 23:21
Duplicate of #5

**Closed as completed by pcperini** 2018-09-11 23:21 UTC
Labels: bug, duplicate
