### ISSUE TITLE
Toot text gets it off after URL

### ISSUE THREAD

**Issue by bl1nk** [pcperini/Tusk---Issues#5] opened 2018-08-30 12:00 UTC
## Expected Behavior
Toot text should be fully visible. 

![e2554ac7-c622-413b-84ac-37ae484ef6ed](https://user-images.githubusercontent.com/663247/44850292-032cbe00-ac5d-11e8-845c-3e2f4da973b1.jpeg)

## Actual Behavior
Toot text is cut off

![1e034c95-64d4-4a4f-a28f-f7eea778a492](https://user-images.githubusercontent.com/663247/44850206-ccef3e80-ac5c-11e8-8ed1-da480b79ecb6.jpeg)

## Steps to Reproduce the Problem

  1. Open the toot at https://mastodon.social/@markus/100639034221072041 in tusk
  1. see it being cut off

## Specifications

  - Version: 1.0.0 (18)

**Comment by lamnatos** [comment] 2018-08-31 08:21
I've seen this too, to me it looks like it "eats" a newline or something, it didn't cut off all of the toot. Also the URL was not tappable (I'll see if there's already an issue for this, if not I'll open one).

It looked like this:

![tusk_toot](https://user-images.githubusercontent.com/178458/44901309-8cdc9a00-acf6-11e8-9260-384da3d55fe4.jpg)

While on the web UI it looked like this:

![web_toot](https://user-images.githubusercontent.com/178458/44901334-9fef6a00-acf6-11e8-9968-94378eae30f6.jpg)

**Comment by pcperini** [comment] 2018-09-03 22:34
Confirmed. This is a pretty straightforward regex issue that will be fixed in a coming build. Thanks!

**Comment by pcperini** [comment] 2018-09-11 23:23
Fixed in b31

**Closed as completed by pcperini** 2018-09-11 23:23 UTC
Labels: bug, :exclamation::exclamation:
